OTA-Firmware-Update: Inital add
contiki-os/contiki pull request #1913
Opened 2016-10-28 16:18 UTC by nenadilic84

Signed-off-by: Nenad Ilic <nenad@relayr.io>

2016-10-30 21:37 UTC, alignan commented
Thanks @nenadilic84 for the PR! I will begin to review shortly

2016-11-01 12:59 UTC, alignan requested changes
A first pass, I will move to test the examples and provide more comments

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/bootloader/project-conf.h
> +
Remove extra spaces here

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/Makefile
> +
Remove extra space

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/hello-world.c
> +
Remove extra space

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/hello-world.c
> +#define DEBUG 0
Why is this `DEBUG` flag and `PRINTF` macro required here?

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/hello-world.c
> +#include <stdio.h>
Depending on the answer above, this directive is duplicated

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/project-conf.h
> + * \addtogroup hello-world app
check the doxygen tags, this one is missing the corresponding closure.  I would add instead to the `zoul-examples` group and create a new group i.e `ota-update` as:
````
/**
 * \addtogroup zoul-examples
 * @{
 *
 * \defgroup ota-update-hello-world Some comment here
 *
 * @{
 * \file
 *         Description here
 */
````

Then at the implemented files just :
````
/**
 * \addtogroup ota-update-hello-world
 * @{
 *  Example description
 * @{
 * \file
 *         Some description here
 * \author
 */
````

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/project-conf.h
> +#define DEVICE_ID                     "Zolertia RE-Mote"
Is this used?

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/bootloader/project-conf.h
> +#define DEVICE_ID                     "Zolertia RE-Mote"
Is this used?

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/bootloader/res/res-firmware.c
> +/**
Doxygen needs some loving here, check out my other review comment with suggestion on setting the tags

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/project-conf.h
> +
Extra space here

2016-11-01 12:59 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/res/res-bootloader.c
> +
Extra space

2016-11-02 08:45 UTC, nenadilic84 commented
@alignan, thanks a lot for the feedback. I'll start addressing the issues.

2016-11-03 15:18 UTC, alignan requested changes
Please also address this comments, I'm now testing! :smile:

2016-11-03 15:18 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/README.md
> +The demo consists of a _bootloader_ and the _hello-world_ applications, each having a single CoAP resource `/firmware` and `/bootloader`, respectivly. Python script `coap_firmware_update.py` is locat
`respectively`

2016-11-03 15:18 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/bootloader/Makefile
> +CONTIKI = ../../../contiki/
`CONTIKI = ../../../../..`

2016-11-03 15:18 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/Makefile
> +CONTIKI = ../../../contiki/
`CONTIKI = ../../../../..`

2016-11-03 15:21 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/hello_world/res/res-bootloader.c
> +                 "Device will reboot to bootloader starting at: 0x%x!",
Replace as follows to avoid warning: "Device will reboot to bootloader starting at: 0x%lx!",

2016-11-03 15:37 UTC, alignan reviewed
Please also include in the `README`:

```
The python script requires the following modules:
CRCMOD: sudo pip install -U crcmod
CoAPthon: https://github.com/Tanganelli/CoAPthon
IntelHex: sudo pip install -U intelhex
```

2016-11-03 15:37 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/README.md
> +The demo consists of a _bootloader_ and the _hello-world_ applications, each having a single CoAP resource `/firmware` and `/bootloader`, respectivly. Python script `coap_firmware_update.py` is locat
located under `tools/zolertia`

2016-11-03 15:37 UTC, alignan commented on examples/zolertia/zoul/ota-firmware-update/README.md
> +In order to flash the newly build application use the `coap_firmware_update.py` located under `tools`
located under ``tools/zolertia``

2016-11-04 08:44 UTC, alignan commented
Cool!  working now :smile:

````
016-11-04 09:34:51,100 - Thread-1   - coapthon.client.coap - DEBUG - send_datagram - From None, To ('aaaa::212:4b00:60d:60f3', 5683), CON-23680, PUT-None, [Uri-Path: firmware, Content-Type: 42, Block1: 13058, ] ...0 bytes
2016-11-04 09:34:51,113 - Thread-1   - coapthon.layers.messagelayer - DEBUG - receive_response - From ('aaaa::212:4b00:60d:60f3', 5683), To None, ACK-23680, BAD_REQUEST-None, [] NoPayload...9 bytes
Dveice secefully updated
````

![screenshot from 2016-11-04 09 42 09](https://cloud.githubusercontent.com/assets/632710/19999522/2cbee91e-a273-11e6-9b5b-a72742cece55.png)

2016-11-04 08:46 UTC, alignan commented on tools/zolertia/coap_firmware_update.py
> +    print("Dveice secefully updated")
`Device successfully updated`

2016-11-23 04:31 UTC, jamesmunns commented
@nenadilic84 @alignan updated the relayr base with @nenadilic84 's newest changes.

Please feel free to ping me directly if you need another refresh :)

2016-11-30 11:00 UTC, alignan commented
Hello! thanks @jamesmunns for the update :smile:

I'm currently refactoring the PR to allow using different wrappers (UDP, MQTT, etc), I will publish my changes on top of this PR for your review as well.

Cheers!

2017-01-30 03:15 UTC, sonvoque commented
cool. It should be nice if this can be merged to Contiki OS master

2026-02-14 12:39 UTC, nenadilic84 commented
Closing - this PR has been stale since 2017 and the project has moved on. Thanks for the original contribution.

2026-02-14 12:39 UTC, closed without merging